name: Deploy webpage

on:
  push:
    branches: [main]
  workflow_dispatch:
  
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install dependencies
        run: sudo apt-get update && sudo apt-get install -y graphviz openjdk-17-jre-headless make

      - name: install sphinx and required utilities
        run: pip install sphinx sphinx-autobuild sphinx-rtd-theme myst-parser sphinxcontrib-mermaid sphinxcontrib-plantuml sphinx-copybutton sphinx-design
     
      - name: build documentation webpage
        run: sphinx-build docs/source docs/_build/html

      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html